apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/jaedolph/gitops-catalog/gpu-operator-certified/aggregate/overlays/default?ref=nvidia-gpu-console-plugin
