apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: istio-ingressgateway
spec:
  port:
    targetPort: http2
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
