apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-cnv
resources:
  - https://github.com/redhat-cop/gitops-catalog/virtualization-operator/base?ref=main
  - hyperconverged.yaml
